version: '3.8'

services:
  backend:
    image: closelocation41/jk-blog-backend:latest  # Using pre-built image
    environment:
      - DATABASE_URI=mongodb://mongo:27017/myblog-mongo
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always

  frontend:
    image: closelocation41/jk-blog-frontend:latest  # Using pre-built image
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
