version: '3.8'

services:
  backend:
    image: 851725574620.dkr.ecr.ap-south-1.amazonaws.com/jk-backend:latest  # Replace with actual ECR URL
    environment:
      - DATABASE_URI=mongodb://mongo:27017/myblog-mongo
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always

  frontend:
    image: 851725574620.dkr.ecr.ap-south-1.amazonaws.com/jk-frontend:latest  # Replace with actual ECR URL
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
