name: Deploy with Docker Compose

on:
  push:
    branches:
      - main  # Deploys when pushing to main branch

jobs:
  build-deploy-run:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Build and push Docker image to ECR
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy and run Docker containers
      run: docker-compose up -d
