name: Deploy to AWS EC2 (Self-Hosted Runner)

on:
  push:
    branches:
      - main  # Trigger deployment on main branch push

jobs:
  deploy:
    runs-on: self-hosted  # Runs on EC2 self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Fetch AWS Secrets from Secrets Manager
        id: get-secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "my-ec2-secrets" --query SecretString --output text)
          echo "$SECRET_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725574620.dkr.ecr.ap-south-1.amazonaws.com

      - name: Pull Latest Docker Images
        run: |
          docker-compose pull

      - name: Restart Docker Services
        run: |
          docker-compose down
          docker-compose up -d --remove-orphans
