name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Clone Backend and Frontend Repositories
      run: |
        git clone https://github.com/closelocation41/jk-frontend.git frontend
        git clone https://github.com/closelocation41/jk-backend.git backend

    - name: Build and Push Docker Images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        BACKEND_REPO: jk-blog-backend
        FRONTEND_REPO: jk-blog-frontend
      run: |
        # Build Backend
        docker build -t $ECR_REGISTRY/$BACKEND_REPO:latest ./backend
        docker push $ECR_REGISTRY/$BACKEND_REPO:latest

        # Build Frontend
        docker build -t $ECR_REGISTRY/$FRONTEND_REPO:latest ./frontend
        docker push $ECR_REGISTRY/$FRONTEND_REPO:latest

    - name: Deploy to AWS EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ubuntu
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          # Install dependencies
          sudo apt update
          sudo apt install -y git docker.io docker-compose awscli

          # Start Docker
          sudo systemctl start docker
          sudo systemctl enable docker

          # Authenticate with ECR
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REGISTRY

          # Pull latest images
          docker pull $ECR_REGISTRY/$BACKEND_REPO:latest
          docker pull $ECR_REGISTRY/$FRONTEND_REPO:latest

          # Update Docker Compose file
          cat <<EOT > /home/ubuntu/docker-compose.yml
          version: '3.8'

          services:
            backend:
              image: $ECR_REGISTRY/$BACKEND_REPO:latest
              ports:
                - "3000:3000"
              restart: always

            frontend:
              image: $ECR_REGISTRY/$FRONTEND_REPO:latest
              ports:
                - "4200:80"
              restart: always
          EOT

          # Start services with Docker Compose
          docker-compose -f /home/ubuntu/docker-compose.yml up -d --force-recreate
        EOF
